core/urls.py
from django.urls import path, include
from core import views

#app_name = 'core'

urlpatterns = [
    #path('', views.indexView, name = 'Pagina Info'),
    path('', views.indexView, name = 'index'),
    #include
    path('publicaciones/', include('publicaciones.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('contacto/', include('contacto.urls')),
   
]

pagina_info/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import RegistroView

app_name = 'usuarios'


urlpatterns = [
    path('login/', LoginView.as_view(template_name = 'usuarios/login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page = '../login'), name='logout'),
    path('registrarse/', RegistroView.as_view(), name='registrarse')
]

usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.


class Usuario(AbstractUser):
    telefono = models.CharField(max_length=12)
    domicilio = models.CharField(max_length=255, blank=True, null=True)
    es_colaborador = models.BooleanField(default=False)
    imagen_perfil = models.ImageField(upload_to = 'imagen_perfil', null=True,blank=True)

usuarios/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import Usuario


#clase que crea un formulario
class RegistrarseForm(UserCreationForm):
    class Meta:
        model = Usuario
        fields = ['first_name', 'last_name', 'username', 'password1', 'password2', 'email', 'telefono', 'domicilio','imagen_perfil']

    # cambiar nombre a las etiquetas

        labels = {
        'first_name' : 'ingrese su nombre',
        'last_name' : 'ingrese su apellido',
    
    }
        
        # tambien podemos agregar calses boostrap con widgets

usuarios/views.py
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic.edit import CreateView
from .models import Usuario
#from django.contrib.auth.forms import UserCreationForm
from .forms import RegistrarseForm
from django.urls import reverse
from django.contrib.auth import login
# Create your views here.

# vista basada en clase que crea un usuario

class RegistroView(CreateView):
    model = Usuario
    template_name = 'usuarios/registro.html'
    form_class = RegistrarseForm

    def get_success_url(self):
        return reverse('index')
    
    def form_valid(self, form):
        respuesta = super().form_valid(form)        # respuesta es algo que ya retornaba la funcion
        usuario = form.save()
        login(self.request, usuario)
        return respuesta

templates/usuarios/login.html
{% extends 'base.html' %}



{% block contenido %}

    <h2>Iniciar Sesion</h2>
    <form method = "post"> {% csrf_token %}

        {{form.as_p}}

        <button type ="submit" class="btn btn-success">Iniciar Sesion</button>


    </form>
    <a href="{% url 'usuarios:registrarse' %}"><button class="btn btn-success mt-2">Create Una Cuenta</button></a>

    
{% endblock contenido %}
    

templates/usuarios/registro.html
{% extends 'base.html' %}


{% block contenido %}

    <h2>Crear un Usuario</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}    
        <button type="submit" class="btn btn-success">Crear Cuenta</button>
    </form> 
{% endblock contenido %}

    