core/urls.py
from django.urls import path, include
from core import views

#app_name = 'core'

urlpatterns = [
    #path('', views.indexView, name = 'Pagina Info'),
    path('', views.indexView, name = 'index'),
    #include
    path('publicaciones/', include('publicaciones.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('contacto/', include('contacto.urls')),
   
]

pagina_info/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

publicaciones/urls.py
from django.urls import path
from publicaciones import views

app_name = 'publicaciones'

urlpatterns = [
    path ("publicaciones/", views.VerPublicaciones.as_view(), name = 'publicaciones'),
    path('postear/', views.Postear.as_view(), name= 'postear'),
    path('editar-post/<int:pk>', views.EditarPost.as_view(), name='editar-post'),
    path('eliminar-post/<int:pk>', views.EliminarPost.as_view(), name='eliminar-post'),
    path('detalle-post/<int:pk>', views.PostDetalle.as_view(), name='detalle-post'),
    path('borrar-comentario/<int:pk>', views.BorrarComentarioView.as_view(), name= 'borrar-comentario'),
    path('me-gusta/', views.me_gusta, name = 'me-gusta')
]

publicaciones/models.py
from django.db import models
from usuarios.models import Usuario
# Create your models here.
#esta clase crea una tabla para guardar categorias
class Categoria(models.Model):
    nombre = models.CharField(max_length=255)



    def __str__(self):
        return self.nombre







#esta clase crea una tabla para publicaciones
class Publicaciones(models.Model):
    fecha = models.DateField(auto_now_add= True)
    update = models.DateField(auto_now=True)
    titulo = models.CharField(max_length=255)
    post = models.TextField()
    categoria = models.ForeignKey(Categoria, on_delete=models.SET_NULL, related_name= 'posteos', null=True)
    creador = models.ForeignKey(Usuario, on_delete= models.CASCADE, related_name='posteos_usuario', default=1)
    meGusta = models.ManyToManyField(Usuario, related_name='publicaciones_gustadas', blank= True)


    def __str__(self):
        return self.titulo
    


class Comentario(models.Model):
    
    fecha = models.DateField(auto_now_add=True)
    post = models.ForeignKey(Publicaciones, on_delete=models.CASCADE, related_name='comentarios')
    autor = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name='comentarios')
    texto = models.TextField(null=True)

    def __str__(self):
        return self.post.titulo + '-' + self.autor.first_name

publicaciones/forms.py
from django import forms
from .models import Publicaciones, Comentario

class CrearPublicacionForm(forms.ModelForm):
    class Meta:
        model = Publicaciones
        fields = ['categoria', 'titulo', 'post']
        labels = {
            'post' : '',
            'titulo': '',
            'categoria': ''

            
        }

        widgets = {
            'titulo': forms.TextInput(attrs= {'placeholder': 'Escribi un Titulo', 'class': 'form-control'}),
            'categoria': forms.Select(attrs={'class' : 'form-select', 'placeholder': 'Categoria'}),
            'post': forms.TextInput(attrs= {'placeholder': '¿En que pensas?', 'class' : 'form-control'})
        }


class ComentarioForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = ['texto']

publicaciones/views.py
from typing import Any
from django.shortcuts import redirect, get_object_or_404
from publicaciones.models import Publicaciones, Comentario, Categoria
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from .forms import CrearPublicacionForm, ComentarioForm
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from core.mixins import SuperusuarioAutorMixin, ColaboradorMixin

# Create your views here.
# pagina de publicaciones


'''# vista basada en funciones
def publicacionesView(request):
    ctx = {
        'posteos' : Publicaciones.objects.all().order_by('fecha')
    }
    return render(request, "publicaciones.html", ctx)'''



# vista basada en clase
class VerPublicaciones(ListView):
    model = Publicaciones
    template_name = 'publicaciones/publicaciones.html'
    context_object_name = 'posteos'
    paginate_by = 3

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) 
        context['categorias'] = Categoria.objects.all
        return context

    #ordenar por fecha
    def get_queryset(self):
        queryset = super().get_queryset()
        # filtramos por categoria
        categoria_seleccionada = self.request.GET.get('categoria')
        if categoria_seleccionada:
            queryset = queryset.filter(categoria = categoria_seleccionada)
        # ordenamos segun criterio
        orden = self.request.GET.get('Ordenar')
        if orden:
            if orden == 'fecha_asc':
                queryset = queryset.order_by('fecha')
            elif orden == 'fecha_desc':
                queryset = queryset.order_by('-fecha')
            elif orden == 'alf_asc':
                queryset = queryset.order_by('titulo')
            elif orden == 'alf_desc':
                queryset = queryset.order_by('-titulo')





        return queryset



    


# view que crea posteos
class Postear(ColaboradorMixin, LoginRequiredMixin, CreateView):
    model = Publicaciones
    template_name = 'publicaciones/postear.html'
    form_class = CrearPublicacionForm


    def get_success_url(self):
        return reverse('publicaciones:publicaciones')
    
    def form_valid(self, form):
        f = form.save(commit= False)        # con evito que guarde el formulario antes de guardar
        f.creador_id = self.request.user.id
        return super().form_valid(f)



# view que modifica posteos
class EditarPost(SuperusuarioAutorMixin,LoginRequiredMixin, UpdateView):
    model = Publicaciones
    template_name = 'publicaciones/editar-post.html'
    form_class = CrearPublicacionForm


    def get_success_url(self):
        return reverse('publicaciones:publicaciones')
    

# view que elimina publicacion

class EliminarPost(SuperusuarioAutorMixin,LoginRequiredMixin,DeleteView):
    model = Publicaciones
    template_name = 'publicaciones/eliminar-post.html'
    
    def get_success_url(self):
        return reverse('publicaciones:publicaciones')
    
    

class PostDetalle(DetailView):
    template_name = 'publicaciones/detalle-post.html'
    model = Publicaciones
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['formulario_comentario'] = ComentarioForm()
        return context
    
    def post(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('usuarios:login')


        publicacion = self.get_object()
        form = ComentarioForm(request.POST)

        if form.is_valid():
            comentario = form.save(commit=False)
            comentario.autor_id = self.request.user.id
            comentario.post = publicacion
            comentario.save()
            return super().get(request)




        else:
            return super().get(request)



class BorrarComentarioView(SuperusuarioAutorMixin, LoginRequiredMixin, DeleteView):
    model = Comentario
    template_name = 'publicaciones/borrar-comentario.html'

    def get_success_url(self):
        return reverse('publicaciones:detalle-post', args = [self.object.post.id])
    




def me_gusta(request):
    if request.method == 'POST':
        publicacion_id = request.POST.get('publicacion_id')
        publicacion = get_object_or_404(Publicaciones, id = publicacion_id)
        usuario = request.user

        if publicacion.meGusta.filter(id=usuario.id).exists():
            publicacion.meGusta.remove(usuario)
        else:
            publicacion.meGusta.add(usuario)

    return redirect('publicaciones:publicaciones')

templates/publicaciones/borrar-comentario.html
{% extends 'base.html' %}



{% block contenido %}

    <form method="post">{% csrf_token %}

        <p>Eliminar Comentario</p>
        <button type="submit" class="btn btn-success">Eliminar</button>



    </form>
    
{% endblock contenido %}
    

templates/publicaciones/detalle-post.html
{% extends 'base.html' %}


{% block contenido %}

    <div class="card" style="width: 18rem;">
        <img src="..." class="card-img-top" alt="...">
        <div class="card-body">
        <p class="card-text">{{ post.fecha }}</p>
        <h6>{{post.creador}}</h6>
        <h5 class="card-title">{{post.titulo}}</h5>
        <p class="card-text">{{ post.post }}</p>
        <a href="#" class="btn btn-primary">Me Gusta</a>
        </div>
    </div>

    <div class="comentarios-container">

        <h2>Comentarios</h2>
        
        {% for comentario in post.comentarios.all %}
            <div class="card">
                <div class="card-body">
                    <h6>{{comentario.autor.first_name}} {{comentario.autor.last_name}}</h6>
                    <p>{{comentario.texto}}</p>

                    
                    {% if user.is_superuser or user == comentario.autor or user == comentario.post.creador %}
                    <a href="{% url 'publicaciones:borrar-comentario' comentario.id %}"><i class="fa-solid fa-trash"></i></a>


                    {% endif %}
                        
                    
                </div>
            </div>
        {% endfor %}
            
       



    </div>




    <form method="post">{% csrf_token %}
        {{ formulario_comentario }}

        <button type="submit">Comentar</button>
    </form>


{% endblock contenido %}

templates/publicaciones/editar-post.html
{% extends 'base.html' %}



{% block contenido %}
    <h2>Editar Posteo</h2>
    
    <form method="post">{% csrf_token %}

        {{form.as_p}}

        <button type="submit" class="btn btn-success">Guardar Cambios</button>
        

    </form>


{% endblock contenido %}
    <h2>Editar Posteo</h2>
    
    <form action=""></form>

templates/publicaciones/eliminar-post.html
{% extends 'base.html' %}



{% block contenido %}

    <form method="post"> {% csrf_token %}

        <p>Estas por Elminar la Publicacion</p>
        <button type="submit" class="btn btn-danger">Eliminar Post</button>

    </form>
    
{% endblock contenido %}


    

templates/publicaciones/postear.html
{% extends 'base.html' %}



{% block contenido %}

<h2>Publicar</h2>
<form method="post">{% csrf_token %}

    {{form.as_p}}
    <button type="submit" class="btn btn-success">Postear</button>



</form>
    
{% endblock contenido %}
    

templates/publicaciones/publicaciones.html
{% extends 'base.html' %}
{% load static %}



{% block contenido %}
<center>
<div class="post-container">

  <form method="get">
    <select name="categoria" id="">
      <option value="">Todas</option>
      {% for categoria in categorias %}
        
      <option value="{{categoria.id}}">{{categoria.nombre}}</option>

      {% endfor %}

    </select>


    <select name="Ordenar" id="">
      <option value="">Ordenar por</option>
      <option value="fecha_asc">Fecha ascendente</option>
      <option value="fecha_desc">Fecha descendente</option>
      <option value="alf_asc">Alfabeticamente ascendente</option>
      <option value="alf_desc">Alfabeticamente descendente</option>



    </select>




      <button type="submit">Filtrar</button>
      
    </center>
        
       



    





  </form>  





    <h2><center>Publicaciones</center></h2>
    
    
    {% if user.is_authenticated and user.es_colaborador or user.is_superuser %}

    <a href="{% url 'publicaciones:postear' %}"><button type="submit" class="btn btn-success mt-3 m-5">Crear Post</button></a>
      
    {% endif %}
      

    
    
    {% for post in posteos %}
        
    
        

    <div class="card m-5">
        <div class="card-header bg-warning">
          {{post.fecha}}
        </div>
        <div class="card-body">
          <h5 class="card-title">{{post.titulo}}</h5>
          <p class="card-text">{{post.post}}</p>
          <p class="card-text">{{post.categoria}}</p>
          <p class="card-text">{{post.creador}}</p>

          <form action="{% url 'publicaciones:me-gusta' %}" method="post">{% csrf_token %}
            <input type="hidden" name="publicacion_id" value="{{post.id}}">

            
            {% if user.is_authenticated %}
              
            
              

            {% if user in post.meGusta.all %}
              <button type="submit" class="btn btn-danger">Ya no me gusta</button>

            {% else %}
             <button type="submit" class="btn btn-success">me gusta!</button>

            {% endif %}
          </form>
          {% endif %}
          <a href="{% url 'publicaciones:detalle-post' post.id %}" class="btn btn-success">Ver Mas</a>

          
          
          {% if user.is_superuser or user == post.creador %}

          <a href="{% url 'publicaciones:editar-post' post.id %}" class="btn btn-success">Editar</a>
          <a href="{% url 'publicaciones:eliminar-post' post.id %}" class="btn btn-danger">Eliminar Post</a>
            





          {% endif %}
          
          



          
        </div>  
      </div>


      {% endfor %}


</div>


<!-- PAGINADOR -->

{% if is_paginated %}

<nav aria-label="Page navigation example" class="mt-5">

    <ul class="pagination">



        
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% else %}
            <li class="page-item">
                <a class="page-link disabled" href="#" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>

        {% endif %}
            
  




        
        {% for pagina in paginator.page_range %}
            <li class="page-item"><a class="page-link {% if page_obj.number == pagina %} active {% endif %}
                " href="?page={{pagina}}">{{ pagina }}</a></li>
        {% endfor %}
            
        




        
        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page= {{ page_obj.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% else %}
            <li class="page-item">
                <a class="page-link disabled" href="#" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>

        {% endif %}
            




    </ul>
</nav>

    
{% endif %}


    
{% endblock contenido %}
    